// App-owned curated common-word list; no runtime fetch; no external license dependency.
const commonWordRankListText = `
A I OF TO IN IS IT BE AS AT SO WE HE BY OR ON DO IF ME MY UP AN GO US NO AM
THE AND FOR ARE BUT NOT YOU ALL ANY CAN HER WAS ONE OUR OUT DAY GET HAS HIM HIS
HOW MAN NEW NOW OLD SEE TWO WAY WHO DID ITS LET PUT SAY SHE TOO USE THAT WITH
HAVE THIS WILL YOUR FROM THEY KNOW WANT BEEN GOOD MUCH SOME TIME VERY WHEN COME
HERE JUST LIKE LONG LOOK MAKE MANY MORE ONLY OVER SUCH TAKE THAN THEM WELL WERE
NEED KEEP EVEN EVER AWAY BACK CALL CAME DEAL DOES DOWN EACH FACE FACT FIND GIVE
HAND HEAD HELP HOME IDEA INTO KIND LIFE LINE LIVE MOVE NAME NEXT ONCE OPEN PART
PLAY ROOM SEEM SHOW SIDE STOP TELL TURN WORK WORD YEAR ABLE AREA BEST BODY BOOK
BOTH CASE CITY DOOR EASY EYES FIRE FOOD FORM FREE GAME GIRL GOES GROW HEAR HOLD
HOPE HOUR HUGE JOIN LAND LATE LESS LIST LOVE MIND MOST MUST NEWS NICE PAST PLAN
REAL REST SAFE SAME SEEN SHIP SHOP SLOW STAR STAY STEP SURE TEAM TERM TEST TEXT
TRUE WALL WEEK WIFE WIND WISH WOOD ZERO THERE WOULD COULD ABOUT AFTER FIRST OTHER
THEIR WHICH THESE THINK GREAT AGAIN STILL EVERY NEVER UNDER MIGHT WHILE WORLD
BEING WHERE THOSE UNTIL SINCE SMALL LARGE RIGHT PLACE POINT FOUND GROUP HOUSE
WOMAN WATER POWER MONEY STORY YOUNG THING STATE TODAY HEART LIGHT VOICE QUITE
WHOLE LOCAL NORTH SOUTH ABOVE BELOW EARLY LATER ALONE ALONG ROUND SENSE HAPPY
SHORT SHOWN START STAND WATCH WRITE READ TRIED BRING BUILD CARRY CAUSE CHECK
CLOSE COVER DREAM DRIVE ENDED ENJOY ENTER FIELD FINAL FORCE GREEN HUMAN ISSUE
LEARN LEAST LEAVE LIVED MAJOR MAYBE MEANS MODEL MUSIC OFTEN ORDER PAPER PARTY
PHONE PIECE PILOT PRESS PRICE REACH READY RIVER SERVE SHARE SHAPE SOUND SPACE
SPEAK SPEND STAGE TABLE THREE TIMES TIRED TOTAL TOUCH TRAIN TRUTH VALUE VISIT
WHITE WORTH YOURS PEOPLE LITTLE SHOULD AROUND BEFORE MOTHER FATHER ALWAYS REALLY
FRIEND FAMILY WITHIN SYSTEM NUMBER PUBLIC THOUGH DURING BETTER BECOME MOMENT
FOLLOW CHANGE ACROSS COURSE ENOUGH PERSON ALMOST RESULT OFFICE MARKET SOCIAL
SCHOOL CHURCH WINDOW LETTER SECOND CHANCE FUTURE SIMPLE COMMON STRONG MEMORY
RETURN GARDEN SILENT BROKEN HIDDEN SEARCH ANSWER REASON NOTICE EITHER CHOICE
INSIDE OUTSIDE FACING BECAUSE BECAME COMING GOING TAKING MAKING SAYING LOOKED
WORKED WALKED PLAYED TURNED OPENED CLOSED BROUGHT THROUGH WITHOUT BETWEEN ANOTHER
NOTHING SOMEONE COUNTRY PROBLEM HOLDING RUNNING HELPING LEAVING FEELING THINKING
FINDING CALLING LOOKING TELLING WORKING READING WRITING TURNING KEEPING SHOWING
OPENING CLOSING PLAYING MOVING LIVING LOVING ENDING STARTING LEARNING WATCHING
LISTENING REMEMBER TOGETHER SOMETHING ANYTHING EVERYONE SOMETIME SOMEWHERE
YOURSELF MYSELF HIMSELF HERSELF OURSELVES MORNING EVENING QUIETLY SOFTLY SUDDENLY
SLOWLY CLEARLY NEARLY SIMPLY DEEPLY HIGHER LOWER CLOSER NEAREST LONGEST WARMER
COLDER MINUTE MONTH STREET TOWN COUNTY COMPANY SERVICE CENTER OFFICE FRONT BACK
CLASS BOARD FLOOR STORE HOTEL STREET PERSON CHILD CHILDREN PARENT SISTER BROTHER
DOCTOR NURSE POLICE COURT JUDGE LAWYER OWNER WORKER DRIVER PLAYER SERVER WRITER
EDITOR READER MEMBER LEADER MANAGER TEACHER STUDENT SUBJECT RECORD REPORT METHOD
ACTION PROJECT PROCESS PROGRAM PRODUCT QUALITY AMOUNT TOTAL LEVEL VALUE RATE COST
PAYMENT ACCOUNT ADDRESS MESSAGE ANSWER QUESTION REQUEST OPTION ORDER SUPPLY DETAIL
EVENT MEETING HISTORY FUTURE PRESENT RECORD RESULT EFFECT SOURCE SERIES PERIOD
SECTION LETTER POLICY REASON PURPOSE CHOICE DECISION SUPPORT CONTROL NOTICE STATUS
PUBLIC PRIVATE GENERAL SPECIAL NORMAL SINGLE DOUBLE COMMON SIMPLE HARD QUICK CLEAR
DIRECT RECENT MODERN STRONG LIGHT HEAVY SHORT LOWER UPPER FULL EMPTY BLACK RED
BLUE WHITE GREEN BROWN YELLOW ORANGE SILVER GROUND TABLE CHAIR WINDOW STREET ROAD
PARK PLACE BUILDING ROOM HOUSE KITCHEN MARKET OFFICE SCHOOL LIBRARY HOSPITAL BANK
STATION AIRPORT TRAIN DRIVER WATER RIVER OCEAN WEATHER SUMMER WINTER SPRING AUTUMN
NIGHT MORNING EVENING TODAY TOMORROW YESTERDAY WEEKEND MINUTE SECOND HOUR MONTH
MIDDLE DIFFICULTY OPPORTUNITY EXPERIENCE KNOWLEDGE UNDERSTAND UNDERSTANDING
`.trim();

const uniqueWords = (input: string): string[] =>
  Array.from(new Set(input.split(/\s+/g))).filter((word) => /^[A-Z]+$/.test(word));

const commonWordRankList: string[] = uniqueWords(commonWordRankListText);

export const commonWordRank = new Map(
  commonWordRankList.map((word, index) => [word, index + 1])
);

export const topCommonWords = new Set(commonWordRankList.slice(0, 220));
export const solverExpansionWords = commonWordRankList.filter(
  (word) => word.length >= 1 && word.length <= 12
);
